services:
  postgres:
    container_name: monolithic-challenge-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: monolithic-challenge-pg
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres